<?php

/**
 * @file
 * This module enables basic Better Search functionality.
 *
 * Provides better looking theming for the Drupal search block.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_form_alter().
 */
function news_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'search_block_form' || $form_id == 'search_form') {
    // Attaching styles.
    $form['#attached']['library'][] = 'news_search/news_search';
    // Adding item.
//    $form['keys']['#suffix'] = '<i class="fas fa-search"></i>';
    $form['keys']['#suffix'] = '<i class="news-search"></i>';
    // Get placeholder name and set into input.
    $placeholder_text = \Drupal::config('news_search.settings')->get('placeholder_text');
    $form['keys']['#attributes']['placeholder'] = t('@placeholder', ['@placeholder' => $placeholder_text]);

    $form['keys']['#attributes']['class'][] = 'input-search';
    $form['actions']['#attributes']['class'][] = 'visually-hidden';
  }
}


