<?php

/**
 * @file
 * This module enables basic Better Search functionality.
 *
 * Provides better looking theming for the Drupal search block.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_form_alter().
 */
function news_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'search_block_form' || $form_id == 'search_form') {
    $theme = \Drupal::config('news_search.settings')->get('theme');
    $form['#attached']['library'][] = 'news_search/news_search';



    if ($form_id == 'search_block_form') {
//      $form['keys']['#prefix'] = '<div class="search__wrapper">';
//      $form['keys']['#suffix'] = '<button type="button" class="btn-search">gfhfghfgh</button>';

//      $form['actions']['#attributes']['id'][] = 'search_submit';
      $placeholder_text = \Drupal::config('news_search.settings')->get('placeholder_text');
      $form['keys']['#attributes']['placeholder'] = t('@placeholder', ['@placeholder' => $placeholder_text]);
      $form['keys']['#attributes']['class'][] = 'input-search';
      $form['actions']['#attributes']['class'][] = 'visually-hidden';
    }

//    if ($form_id == 'search_form') {
//      $form[$key]['keys']['#suffix'] = '<div class="icon"><i class="better_search"></i></div>';
//
//
//      $placeholder_text = \Drupal::config('better_search.settings')->get('placeholder_text');
//      $form[$key]['keys']['#attributes']['placeholder'] = t('@placeholder', ['@placeholder' => $placeholder_text]);
//
//      $submit_not_visible = \Drupal::config('better_search.settings')->get('searchpage_submit_not_visible');
//
//      if ($submit_not_visible) {
//
//        /*
//         * Works with Bartik
//         */
//
//        /** @var \Drupal\Core\Theme\ActiveTheme $theme */
//        $theme = \Drupal::service('theme.manager')->getActiveTheme();
//        $main_theme = $theme->getName();
//        $base_themes = $theme->getBaseThemeExtensions();
//
//        if ($main_theme == "bootstrap" || array_key_exists('bootstrap', $base_themes)){
//          /* Works with Bootstrap */
//
//          $form[$key]['submit']['#attributes'] = [
//            'class' => ['visually-hidden'],
//          ];
//
//        }else{
//          /* Works with other themes */
//          if (!isset($form[$key]['submit']['#attributes'])) {
//            $form[$key]['submit']['#attributes'] = new Attribute();
//          }
//          $form[$key]['submit']['#attributes']->addClass('visually-hidden');
//        }
//
//      }
//      $form[$key]['keys']['#size'] = \Drupal::config('better_search.settings')->get('size');
//
//    }
  }
}

/**
 * Implements news_search_preprocess_form_element().
 */
//function news_search_preprocess_form_element(&$variables) {
//  if ($variables['element']['#type'] == 'search') {
//    $variables['attributes'] = ['class' => ['clearfix', 'mt-3 inputs']];
//  }
//}
