google_news_api_key: b82cef6a27f0433db3bc2f01a03199bd
top_head_settings:
  countries: 'us, uk, gb'
  categories: 'business, entertainment, general, health, science, sports, technology'
  sources: ''
  content_type: google_news
  comparison:
    body: content
    field_author: author
    field_banner: ''
    field_description: description
    field_external_url: url
    field_published_at: publishedAt
    field_remote_image: urlToImage
    field_source_name: source
    field_type: ''
everything_settings:
  sources: ''
  searchIn: 'title, content, description'
  domains: ''
  exclude_domains: ''
  languages: 'en, ua'
  content_type: google_news
  comparison:
    body: content
    field_author: author
    field_banner: ''
    field_description: description
    field_external_url: url
    field_published_at: publishedAt
    field_remote_image: urlToImage
    field_source_name: source
    field_type: ''
_core:
  default_config_hash: 1DtI4GWOoaARFacpwf9W1Afx697peBE61azi3pQAZic
