google_news_api_key: b82cef6a27f0433db3bc2f01a03199bd
top_head_settings:
  frequency: '120'
  countries: 'ua, us, en'
  categories: 'business, entertainment, general, health, science, sports, technology'
  q_keys: ''
  sources: ''
  page_size: '20'
  page: '1'
everything_settings:
  frequency: '360'
  q_keys: '"Google News", "УНІАН", "Українська правда", "ТСН", "BBC Україна", "Радіо Свобода", "РБК-Украина", "The Independent", "The Guardian, Sky News", "The Times"'
  sources: ''
  searchIn: ''
  domains: ''
  exclude_domains: ''
  languages: 'en, ua'
  sort_by: popularity
  page_size: '100'
  page: '1'
_core:
  default_config_hash: sUQsnMzvIA5ZGMOfkaCZjOeZNw7jkhVq-PNKM41cDNw
