_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: smtp.ukr.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: false
smtp_timeout: 30
smtp_username: roomaan_3@ukr.net
smtp_password: HgoV5OHVFM71xkL8
smtp_from: roomaan_3@ukr.net
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: romachehdkdk@gmail.com
smtp_reroute_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
