features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/wiw_theme/images/optimized/logo32.svg
favicon:
  use_default: 0
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
b5_top_container: container
b5_top_container_config: ''
b5_body_schema: none
b5_body_bg_schema: none
b5_navbar_schema: none
b5_navbar_bg_schema: none
b5_footer_schema: none
b5_footer_bg_schema: none
subtheme_folder: themes/custom
subtheme_name: 'B5 subtheme'
subtheme_machine_name: b5subtheme
