features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: themes/custom/wiw_theme/images/optimized/logo32.svg
  url: ''
  use_default: 0
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: /sites/default/files/favicon.ico
  use_default: 0
b5_top_container: container
b5_top_container_config: ''
b5_body_schema: none
b5_body_bg_schema: none
b5_navbar_schema: none
b5_navbar_bg_schema: none
b5_footer_schema: none
b5_footer_bg_schema: none
subtheme_folder: themes/custom
subtheme_name: 'B5 subtheme'
subtheme_machine_name: b5subtheme
schemas:
  bootstrap: 8000
  wiw_theme: 8000
