<?php

/**
 * @file
 * Twig template for render content
 */
function news_core_theme($existing, $type, $theme, $path) {

  return [
    'top_headlines' => [
      'variables' => [
        'list' => [],
      ],
    ],
    'everything' => [
      'variables' => [
        'list' => [],
      ],
    ],
  ];

}

function news_core_preprocess_block__top_headlines_block(&$variables): void {
  $variables['timer'] = date('l', time()) . ', ' . date('j F', time());
}
